# Generated by Django 4.1.2 on 2022-10-16 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0001_initial'),
        ('labels', '0001_initial'),
        ('tasks', '0006_alter_tasks_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labeled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.labels')),
            ],
            options={
                'db_table': 'tasks_task_label',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executive', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(through='tasks.Labeled', to='labels.labels')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='statuses.statuses')),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='labeled',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task'),
        ),
    ]
