# Generated by Django 4.1.2 on 2022-10-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_labeled_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_column='title', max_length=255),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
