# Generated by Django 4.1.2 on 2022-10-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(db_column='title', max_length=255),
        ),
        migrations.RenameField(
            model_name='label',
            old_name='title',
            new_name='name',
        ),
    ]
