# Generated by Django 4.1.2 on 2022-10-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_label_title_rename_title_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
